#!/usr/bin/env python3
"""
Test the SSE fix with a simple blog generation
"""
import requests
import json
import warnings
warnings.filterwarnings('ignore', message='Unverified HTTPS request')

def test_sse_fix():
    """Test the SSE fix by starting a blog generation"""
    
    # Read the JWT token from file (generated by generate_valid_jwt.py)
    try:
        with open('valid_jwt_token.txt', 'r') as f:
            token = f.read().strip()
    except FileNotFoundError:
        print("❌ JWT token file not found. Please run: python generate_valid_jwt.py")
        return False
    
    # Start a blog generation
    payload = {
        'topic': 'SSE Fix Test - Real-time Updates',
        'instructions': 'Generate a brief test blog to verify our SSE streaming fix works correctly.'
    }
    
    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json'
    }
    
    print('🚀 Starting blog generation to test SSE fix...')
    try:
        response = requests.post('https://localhost:5000/generate-blog', 
                                json=payload, headers=headers, verify=False, timeout=10)
        
        if response.status_code == 200:
            result = response.json()
            task_id = result['task_id']
            print(f'✅ Blog generation started with task ID: {task_id}')
            print(f'📡 Test SSE stream with: curl -k "https://localhost:5000/stream/{task_id}?token={token}"')
            print(f'🎯 Frontend can now connect to: https://localhost:3001 and start a blog generation')
            print(f'⏳ This should now work without SSE timeouts!')
            return True
        else:
            print(f'❌ Failed to start blog generation: {response.status_code} - {response.text}')
            return False
    
    except requests.exceptions.RequestException as e:
        print(f'❌ Request failed: {e}')
        return False

if __name__ == "__main__":
    success = test_sse_fix()
    if success:
        print("\n🎉 Test initiated successfully!")
        print("💡 The SSE timeout issue should now be resolved.")
        print("📝 Monitor backend logs to confirm Redis updates and database completion.")
    else:
        print("\n💥 Test failed - check the backend server and JWT token.")
