research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure you find any interesting and relevant information given the current year is {current_year}. 
    You should focus on the top 5 most relevant information about {topic} that is available in the current year.
    You should also include references to the source material you used in your research.    
  expected_output: >
    Comprehensive summary report of the top 5 most relevant information about {topic}.
  agent: researcher

content_generation_task:
  description: >
    Based on the summary report provided by the researcher, generate a draft blog that properly lays out and presents the content in an engaging and easy to understand manner.
  expected_output: >
    A fully fledged draft blog with the main topics, each with a full section of information and reference to source material.    
  
fact_checking_task:
  description: >
    Conduct a independent research about {topic} this time focusing on making sure you only use verified sources (meaning more than 1 source of information). Review the draft blog generated by the content creator to make sure it only references the verified sources you found.
  expected_output: >
    A list of specific topics and verified sources that the researcher should use to reverify their research.
  
content_finalization_task:
  description: >
    Generate the final draft blog in an engaging, well structured and easy to understand format. All references to verified source data should be properly referenced in each applicable sentence. The end of the blog should include special references section, with titles and links to source materials. The final blog should be formatted as markdown without '```'
  expected_output: >
    Final generated blog with will structured, eye catching material and references to source material, and generated as a Markdown file.